### ISSUE TITLE
Support for Android 13

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [whew-inc/FakeGApps#10]
After upgrade to Android 13, it seems like the App cannot work on Android 13. As the micro-g self-check indicates that signature-proofing is not supported.
It is not the case on Android 12/12.1

**Comment by Wojtaz0w** [comment]
Same problem here
----part 1 start----
[ 2022-09-14T07:57:13.718     1000:  1275:  1275 I/LSPosed-Bridge  ] Loading module inc.whew.android.fakegapps from /data/app/~~RAr1lViM8nhRcBWqTM4QbQ==/inc.whew.android.fakegapps-n1ykvUHqbkRhopR1Xs8ugQ==/base.apk
[ 2022-09-14T07:57:13.720     1000:  1275:  1275 I/LSPosed-Bridge  ]   Loading class inc.whew.android.fakegapps.FakeSignatures
[ 2022-09-14T07:57:14.284     1000:  1275:  1275 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService.ComputerEngine
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at inc.whew.android.fakegapps.FakeSignatures.handleLoadPackage(FakeSignatures.java:37)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at r.beforeHookedMethod(Unknown Source:3)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:937)
	at com.android.server.SystemServer.main(SystemServer.java:649)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:914)
Caused by: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService.ComputerEngine
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at p.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService.ComputerEngine
	... 16 more

**Comment by whew-inc** [comment]
Woops. Does v2 work? https://github.com/whew-inc/FakeGApps/releases/tag/lsposed

**Comment by JaneValleyhasBtaken** [comment]
Ob wow, I can confirm this version works. Like, how!

**Comment by Wojtaz0w** [comment]
Yeah, it works for me too! Thanks for helping :)

**Comment by JaneValleyhasBtaken** [comment]
Closed since the issue is resolved

**Comment by whew-inc** [comment]
Latest release supports Android 13.

https://github.com/whew-inc/FakeGApps/releases/tag/4.3
