### ISSUE TITLE
Release 4.1 not working on Android 12 (LineageOS 19.1)

### ISSUE THREAD

**Issue by diamant711** [whew-inc/FakeGApps#8]
Hi! Thanks for updating the module! The FakeGApps don't work and I see an error in the LSposed log.

`E/AndroidRuntime] FATAL EXCEPTION: pool-3-thread-3`

Right after the loading of the module (i don't know if the error is related to the module).
Is there any fix to this?
Thanks in advance!

PS: I am avaible for any further information if needed :)

**Comment by whew-inc** [comment]
Hi and thank you!

Does the error persist after disabling the module?
Also please post full xposed log.

**Comment by diamant711** [comment]
Hi! Thanks for the reply. 
I'm new to the Android system, is it safe to attach the full.log file publicly here?

**Comment by whew-inc** [comment]
Yes, xposed logs shouldn't contain anything sensitive.

**Comment by diamant711** [comment]
Ok!
```
$ cat verbose_1970-09-26T21:36:43.217.log
----part 1 start----
[ 1970-09-26T21:36:40.581        0:   542:   542 I/Magisk          ] Magisk 25.2(25200) daemon started
[ 1970-09-26T21:36:40.582        0:   542:   542 I/Magisk          ] * Device API level: 32
[ 1970-09-26T21:36:40.612        0:   542:   544 I/Magisk          ] ** post-fs-data mode running
[ 1970-09-26T21:36:40.614        0:   542:   544 I/Magisk          ] * Mounting mirrors
[ 1970-09-26T21:36:40.615        0:   542:   544 I/Magisk          ] mount: /dev/Pna/.magisk/mirror/vendor
[ 1970-09-26T21:36:40.615        0:   542:   544 I/Magisk          ] link: /dev/Pna/.magisk/mirror/cache
[ 1970-09-26T21:36:40.615        0:   542:   544 I/Magisk          ] link: /dev/Pna/.magisk/mirror/persist
[ 1970-09-26T21:36:40.615        0:   542:   544 I/Magisk          ] mount: /dev/Pna/.magisk/mirror/data
[ 1970-09-26T21:36:40.615        0:   542:   544 I/Magisk          ] link: /dev/Pna/.magisk/mirror/system
[ 1970-09-26T21:36:40.616        0:   542:   544 I/Magisk          ] mount: /dev/Pna/.magisk/mirror/system_root
[ 1970-09-26T21:36:40.616        0:   542:   544 I/Magisk          ] link: /dev/Pna/.magisk/mirror/product
[ 1970-09-26T21:36:40.616        0:   542:   544 I/Magisk          ] link: /dev/Pna/.magisk/mirror/system_ext
[ 1970-09-26T21:36:40.710        0:   542:   544 I/Magisk          ] * Initializing Magisk environment
[ 1970-09-26T21:36:40.824        0:   542:   544 I/Magisk          ] * Running post-fs-data.d scripts
[ 1970-09-26T21:36:40.833        0:   542:   544 I/Magisk          ] * Running module post-fs-data scripts
[ 1970-09-26T21:36:40.835        0:   549:   549 I/Magisk          ] riru_lsposed: exec [post-fs-data.sh]
[ 1970-09-26T21:36:40.858        0:   549:   549 I/Magisk          ] riru-core: exec [post-fs-data.sh]
[ 1970-09-26T21:36:40.916        0:   542:   544 I/Magisk          ] * Loading modules
[ 1970-09-26T21:36:40.916        0:   542:   544 I/Magisk          ] riru-core: loading [system.prop]
[ 1970-09-26T21:36:40.917        0:   542:   544 I/Magisk          ] riru-core: loading mount files
[ 1970-09-26T21:36:40.918        0:   542:   544 I/Magisk          ] microg_installer: loading mount files
[ 1970-09-26T21:36:40.918        0:   542:   544 I/Magisk          ] hosts: loading mount files
[ 1970-09-26T21:36:40.918        0:   542:   544 I/Magisk          ] HideNavBar: loading mount files
[ 1970-09-26T21:36:40.927        0:   542:   544 W/Magisk          ] Unable to add: /vendor/overlay, skipped
[ 1970-09-26T21:36:41.634        0:   554:   554 D/AndroidRuntime  ] >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
[ 1970-09-26T21:36:41.643        0:   554:   554 I/AndroidRuntime  ] Using default boot image
[ 1970-09-26T21:36:41.643        0:   554:   554 I/AndroidRuntime  ] Leaving lock profiling enabled
[ 1970-09-26T21:36:41.651        0:   554:   554 W/lspd            ] ART APEX data files are untrusted.
[ 1970-09-26T21:36:41.651        0:   554:   554 I/lspd            ] Core platform API reporting enabled, enforcing=false
[ 1970-09-26T21:36:41.930        0:   581:   581 I/Riru64          ] Riru v26.1.4 (522) in zygote64
[ 1970-09-26T21:36:41.930        0:   581:   581 I/Riru64          ] Android 12 (api 32, preview_api 0)
[ 1970-09-26T21:36:41.930        0:   581:   581 W/Riru64          ] retrying to connect rirud in 1s
[ 1970-09-26T21:36:42.017        0:   554:   554 D/lspd            ] Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
[ 1970-09-26T21:36:42.018        0:   554:   554 D/lspd            ] I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt68l.dat
[ 1970-09-26T21:36:42.744        0:   582:   582 I/Riru            ] Riru v26.1.4 (522) in zygote
[ 1970-09-26T21:36:42.745        0:   582:   582 I/Riru            ] Android 12 (api 32, preview_api 0)
[ 1970-09-26T21:36:42.745        0:   582:   582 W/Riru            ] retrying to connect rirud in 1s
[ 1970-09-26T21:36:42.931        0:   581:   581 W/Riru64          ] retrying to connect rirud in 1s
[ 1970-09-26T21:36:43.001        0:   554:   554 D/AndroidRuntime  ] Calling main entry org.lsposed.lspd.Main
[ 1970-09-26T21:36:43.015        0:   568:   840 I/RiruDaemon      ] Set socket context to u:r:zygote:s0
[ 1970-09-26T21:36:43.015        0:   568:   840 D/RiruDaemon      ] Start server
[ 1970-09-26T21:36:43.042        0:   568:   840 D/RiruDaemon      ] Accept
[ 1970-09-26T21:36:43.097        0:   554:   554 I/LSPosedService  ] starting server...
[ 1970-09-26T21:36:43.167        0:   554:   554 I/LSPosedService  ] version 1.8.3 (6552)
[ 1970-09-26T21:36:43.216        0:   554:   871 I/LSPosedLogcat   ] start running
[ 1970-09-26T21:36:43.218        0:   554:   871 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_1970-09-26T21:36:43.217.log
[ 1970-09-26T21:36:43.254        0:   554:   871 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_1970-09-26T21:36:43.253.log
[ 1970-09-26T21:36:43.297        0:   554:   554 W/LSPosedDex2Oat  ] Check mount failed for /apex/com.android.art/bin/dex2oat32
[ 1970-09-26T21:36:43.297        0:   878:   554 I/LSPosed         ] Enable dex2oat wrapper
[ 1970-09-26T21:36:43.299        0:   554:   880 I/LSPosedDex2Oat  ] Daemon start
[ 1970-09-26T21:36:43.315        0:   554:   554 W/SQLiteCompatibilityWalFlags ] Cannot read global setting sqlite_compatibility_wal_flags - Application state not available
[ 1970-09-26T21:36:43.400        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/lib64/libriru.so
[ 1970-09-26T21:36:43.400        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/lib64/libriruhide.so
[ 1970-09-26T21:36:43.400        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/lib64
[ 1970-09-26T21:36:43.400        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core
[ 1970-09-26T21:36:43.401        0:   568:   883 D/RiruDaemon      ] /dev/Pna/.magisk/modules/riru_lsposed is a Riru module
[ 1970-09-26T21:36:43.401        0:   568:   882 D/RiruDaemon      ] /dev/Pna/.magisk/modules/riru_lsposed is a Riru module
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/system/lib64/libriruloader.so
[ 1970-09-26T21:36:43.401        0:   568:   883 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed/riru/lib/liblspd.so
[ 1970-09-26T21:36:43.401        0:   568:   882 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed/riru/lib64/liblspd.so
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/system/lib64
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/system
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core
[ 1970-09-26T21:36:43.401        0:   568:   883 D/RiruDaemon      ] Path for riru_lsposed@lspd is /dev/Pna/.magisk/modules/riru_lsposed/riru/lib/liblspd.so
[ 1970-09-26T21:36:43.401        0:   568:   883 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed/riru/lib
[ 1970-09-26T21:36:43.401        0:   568:   883 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed/riru
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/lib/libriru.so
[ 1970-09-26T21:36:43.401        0:   568:   883 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/lib/libriruhide.so
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/lib
[ 1970-09-26T21:36:43.401        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core
[ 1970-09-26T21:36:43.402        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/system/lib/libriruloader.so
[ 1970-09-26T21:36:43.402        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/system/lib
[ 1970-09-26T21:36:43.402        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core/system
[ 1970-09-26T21:36:43.402        0:   568:   568 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru-core
[ 1970-09-26T21:36:43.404        0:   568:   882 D/RiruDaemon      ] Path for riru_lsposed@lspd is /dev/Pna/.magisk/modules/riru_lsposed/riru/lib64/liblspd.so
[ 1970-09-26T21:36:43.404        0:   568:   882 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed/riru/lib64
[ 1970-09-26T21:36:43.404        0:   568:   882 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed/riru
[ 1970-09-26T21:36:43.404        0:   568:   882 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/Pna/.magisk/modules/riru_lsposed
[ 1970-09-26T21:36:43.444        0:   568:   568 I/RiruDaemon      ] Magisk version is 25200
[ 1970-09-26T21:36:43.445        0:   568:   568 I/RiruDaemon      ] Magisk tmpfs path is /dev/Pna
[ 1970-09-26T21:36:43.445        0:   568:   568 I/RiruDaemon      ] Original native bridge is 0
[ 1970-09-26T21:36:43.446        0:   568:   568 I/RiruDaemon      ] Read dev random typKp8X
[ 1970-09-26T21:36:43.446        0:   568:   568 I/RiruDaemon      ] Dev random is typKp8X
[ 1970-09-26T21:36:43.447        0:   568:   568 I/RiruDaemon      ] clear ServiceManager
[ 1970-09-26T21:36:43.453        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 1970-09-26T21:36:43.489        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 1970-09-26T21:36:43.746        0:   568:   840 D/RiruDaemon      ] Accepted uid=0, pid=582, context=u:r:zygote:s0
[ 1970-09-26T21:36:43.747        0:   568:   840 D/RiruDaemon      ] Accept
[ 1970-09-26T21:36:43.749        0:   568:   938 I/RiruDaemon      ] Action 6
[ 1970-09-26T21:36:43.749        0:   568:   938 I/RiruDaemon      ] Action: read Magisk tmpfs path
[ 1970-09-26T21:36:43.749        0:   568:   938 I/RiruDaemon      ] Handle action 6 finished
[ 1970-09-26T21:36:43.783        0:   582:   582 I/Riru            ] hook installed
[ 1970-09-26T21:36:43.783        0:   582:   582 I/Riru            ] no jniRegisterNativeMethods
[ 1970-09-26T21:36:43.788        0:   582:   582 I/Riru            ] override table installed
[ 1970-09-26T21:36:43.789        0:   568:   938 I/RiruDaemon      ] Action 7
[ 1970-09-26T21:36:43.789        0:   568:   938 I/RiruDaemon      ] Action: read modules
[ 1970-09-26T21:36:43.791        0:   568:   938 I/RiruDaemon      ] Handle action 7 finished
[ 1970-09-26T21:36:43.794        0:   582:   582 I/Riru            ] module loaded: riru_lsposed@lspd (api 25)
[ 1970-09-26T21:36:43.816        0:   582:   582 I/LSPosed         ] onModuleLoaded: welcome to LSPosed!
[ 1970-09-26T21:36:43.816        0:   582:   582 I/LSPosed         ] onModuleLoaded: version v1.8.3 (6552)
[ 1970-09-26T21:36:43.842        0:   568:   938 I/RiruDaemon      ] Action 2
[ 1970-09-26T21:36:43.843        0:   568:   938 I/RiruDaemon      ] Action: write status
[ 1970-09-26T21:36:43.860        0:   568:   938 I/RiruDaemon      ] Handle action 2 finished
[ 1970-09-26T21:36:43.860        0:   568:   938 I/RiruDaemon      ] No next action, exiting...
[ 1970-09-26T21:36:43.931        0:   568:   840 D/RiruDaemon      ] Accepted uid=0, pid=581, context=u:r:zygote:s0
[ 1970-09-26T21:36:43.932        0:   568:   840 D/RiruDaemon      ] Accept
[ 1970-09-26T21:36:43.940        0:   568:   986 I/RiruDaemon      ] Action 6
[ 1970-09-26T21:36:43.940        0:   568:   986 I/RiruDaemon      ] Action: read Magisk tmpfs path
[ 1970-09-26T21:36:43.942        0:   568:   986 I/RiruDaemon      ] Handle action 6 finished
[ 1970-09-26T21:36:43.978        0:   581:   581 I/Riru64          ] hook installed
[ 1970-09-26T21:36:43.978        0:   581:   581 I/Riru64          ] no jniRegisterNativeMethods
[ 1970-09-26T21:36:43.987        0:   581:   581 I/Riru64          ] override table installed
[ 1970-09-26T21:36:43.996        0:   568:   986 I/RiruDaemon      ] Action 7
[ 1970-09-26T21:36:43.996        0:   568:   986 I/RiruDaemon      ] Action: read modules
[ 1970-09-26T21:36:43.997        0:   568:   986 I/RiruDaemon      ] Handle action 7 finished
[ 1970-09-26T21:36:44.002        0:   581:   581 I/Riru64          ] module loaded: riru_lsposed@lspd (api 25)
[ 1970-09-26T21:36:44.024        0:   581:   581 I/LSPosed         ] onModuleLoaded: welcome to LSPosed!
[ 1970-09-26T21:36:44.024        0:   581:   581 I/LSPosed         ] onModuleLoaded: version v1.8.3 (6552)
[ 1970-09-26T21:36:44.061        0:   568:   986 I/RiruDaemon      ] Action 2
[ 1970-09-26T21:36:44.061        0:   568:   986 I/RiruDaemon      ] Action: write status
[ 1970-09-26T21:36:44.082        0:   582:   582 I/Riru            ] replaced com.android.internal.os.Zygote#nativeForkAndSpecialize
[ 1970-09-26T21:36:44.082        0:   582:   582 I/Riru            ] replaced com.android.internal.os.Zygote#nativeForkSystemServer
[ 1970-09-26T21:36:44.082        0:   582:   582 I/Riru            ] replaced com.android.internal.os.Zygote#nativeSpecializeAppProcess
[ 1970-09-26T21:36:44.117        0:   568:   986 I/RiruDaemon      ] Handle action 2 finished
[ 1970-09-26T21:36:44.117        0:   568:   986 I/RiruDaemon      ] No next action, exiting...
[ 1970-09-26T21:36:44.163        0:   581:   581 I/Riru64          ] replaced com.android.internal.os.Zygote#nativeForkAndSpecialize
[ 1970-09-26T21:36:44.164        0:   581:   581 I/Riru64          ] replaced com.android.internal.os.Zygote#nativeForkSystemServer
[ 1970-09-26T21:36:44.164        0:   581:   581 I/Riru64          ] replaced com.android.internal.os.Zygote#nativeSpecializeAppProcess
[ 2022-08-10T10:36:38.642        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:38.678        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:39.190        0:   542:   544 I/Magisk          ] ** late_start service mode running
[ 2022-08-10T10:36:39.190        0:   542:   544 I/Magisk          ] * Running service.d scripts
[ 2022-08-10T10:36:39.190        0:   542:   544 I/Magisk          ] * Running module service scripts
[ 2022-08-10T10:36:39.190        0:   542:   544 I/Magisk          ] riru_lsposed: exec [service.sh]
[ 2022-08-10T10:36:39.207        0:   542:   544 I/Magisk          ] riru-core: exec [service.sh]
[ 2022-08-10T10:36:39.223        0:   542:   544 I/Magisk          ] HideNavBar: exec [service.sh]
[ 2022-08-10T10:36:39.643        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:39.678        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:40.644        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:40.679        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:41.645        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:41.681        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:42.646        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:42.681        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:43.646        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:43.682        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:44.421     1000:  1670:  1670 I/LSPosed         ] Loading xposed for android/1000
[ 2022-08-10T10:36:44.543     1000:  1670:  1670 I/LSPosed-Bridge  ] Loading module ru.mcdvuayq.laupagpjl from /data/app/~~KT81P8ykNAlpzs6fAG0-ig==/ru.mcdvuayq.laupagpjl-RpbfD7o7FDFh3bUYTRZqBQ==/base.apk
[ 2022-08-10T10:36:44.647        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:44.666     1000:  1670:  1670 I/LSPosed-Bridge  ]   Loading class com.xposed.XSupport
[ 2022-08-10T10:36:44.682        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:45.648        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:45.683        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:46.648        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:46.683        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:47.649        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:47.684        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:48.650        0:   568:   568 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2022-08-10T10:36:48.684        0:   554:   554 I/LSPosedService  ] service package is not started, wait 1s.
[ 2022-08-10T10:36:49.492        0:   554:   879 I/LSPosedService  ] manager is not installed
[ 2022-08-10T10:36:49.682        0:   568:   568 I/RiruDaemon      ] Riru loaded, reset native bridge to 0...
[ 2022-08-10T10:36:49.697        0:   568:   568 I/RiruDaemon      ] Exec resetprop exited with 0
[ 2022-08-10T10:36:49.697        0:   568:   568 I/RiruDaemon      ] Riru loaded, stop rirud socket...
[ 2022-08-10T10:36:49.697        0:   568:   568 I/RiruDaemon      ] Stop server
[ 2022-08-10T10:36:49.697        0:   568:   568 I/RiruDaemon      ] Server stopped
[ 2022-08-10T10:36:49.697        0:   568:   840 I/RiruDaemon      ] Server shutdown.
[ 2022-08-10T10:36:49.697        0:   568:   840 I/RiruDaemon      ] Waiting for restart server...
[ 2022-08-10T10:36:49.698     1000:  1670:  1735 I/LSPosed Bridge  ] binder received
[ 2022-08-10T10:36:49.699        0:   554:   554 I/LSPosedService  ] sent service to bridge
[ 2022-08-10T10:36:57.373        0:   554:  1847 E/LSPosedService  ] Broadcast to manager failed: 
java.lang.NoSuchMethodError: No interface method broadcastIntentWithFeature(Landroid/app/IApplicationThread;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/content/IIntentReceiver;ILjava/lang/String;Landroid/os/Bundle;[Ljava/lang/String;[Ljava/lang/String;ILandroid/os/Bundle;ZZI)I in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)
	at f0.a(Unknown Source:37)
	at h1.a(Unknown Source:40)
	at n1.a(Unknown Source:26)
	at n1.b(Unknown Source:8)
	at E1.run(Unknown Source:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
[ 2022-08-10T10:36:58.662        0:   554:  1847 E/LSPosedService  ] Broadcast to manager failed: 
java.lang.NoSuchMethodError: No interface method broadcastIntentWithFeature(Landroid/app/IApplicationThread;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/content/IIntentReceiver;ILjava/lang/String;Landroid/os/Bundle;[Ljava/lang/String;[Ljava/lang/String;ILandroid/os/Bundle;ZZI)I in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)
	at f0.a(Unknown Source:37)
	at h1.a(Unknown Source:40)
	at n1.a(Unknown Source:26)
	at n1.b(Unknown Source:8)
	at E1.run(Unknown Source:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
[ 2022-08-10T10:37:03.644        0:   542:   544 I/Magisk          ] ** boot-complete triggered
[ 2022-08-10T10:38:01.130        0:   554:   879 I/LSPosed         ] verifyInstallerSignature: true
[ 2022-08-10T10:38:01.157     2000:  6035:  6035 I/LSPosed         ] Loaded manager, skipping next steps
[ 2022-08-10T10:38:01.252     2000:  6035:  6035 I/LSPosed         ] Found LSPosed Manager
[ 2022-08-10T10:38:01.255     2000:  6035:  6035 I/LSPosed         ] Send binder to LSPosed Manager: true
[ 2022-08-10T10:38:31.829    10172:  7732:  7732 I/LSPosed         ] Loading xposed for ru.mcdvuayq.laupagpjl/10172
[ 2022-08-10T10:38:31.854    10172:  7732:  7732 I/LSPosed-Bridge  ] Loading module ru.mcdvuayq.laupagpjl from /data/app/~~KT81P8ykNAlpzs6fAG0-ig==/ru.mcdvuayq.laupagpjl-RpbfD7o7FDFh3bUYTRZqBQ==/base.apk
[ 2022-08-10T10:38:32.025    10172:  7732:  7732 I/LSPosed-Bridge  ]   Loading class com.xposed.XSupport
[ 2022-08-10T10:39:02.902    50143: 10313: 10313 I/LSPosedDex2Oat  ] dex2oat wrapper
[ 2022-08-10T10:39:03.395        0:   554:  1847 E/LSPosedService  ] Broadcast to manager failed: 
java.lang.NoSuchMethodError: No interface method broadcastIntentWithFeature(Landroid/app/IApplicationThread;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/content/IIntentReceiver;ILjava/lang/String;Landroid/os/Bundle;[Ljava/lang/String;[Ljava/lang/String;ILandroid/os/Bundle;ZZI)I in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)
	at f0.a(Unknown Source:37)
	at h1.a(Unknown Source:40)
	at n1.a(Unknown Source:26)
	at n1.b(Unknown Source:8)
	at E1.run(Unknown Source:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
[ 2022-08-10T10:39:03.418        0:   554:  1847 W/System          ] No Compatibility callbacks set! Querying change 160794467
[ 2022-08-10T10:39:03.496        0:   554: 10333 E/LSPosedService  ] Broadcast to manager failed: 
java.lang.NoSuchMethodError: No interface method broadcastIntentWithFeature(Landroid/app/IApplicationThread;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/content/IIntentReceiver;ILjava/lang/String;Landroid/os/Bundle;[Ljava/lang/String;[Ljava/lang/String;ILandroid/os/Bundle;ZZI)I in class Landroid/app/IActivityManager; or its super classes (declaration of 'android.app.IActivityManager' appears in /system/framework/framework.jar)
	at f0.a(Unknown Source:37)
	at h1.a(Unknown Source:40)
	at n1.a(Unknown Source:26)
	at n1.b(Unknown Source:8)
	at E1.run(Unknown Source:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
[ 2022-08-10T10:39:03.500        0:   554: 10333 W/System          ] No Compatibility callbacks set! Querying change 160794467
[ 2022-08-10T10:39:10.300        0:   554:   869 W/lspd            ] Long monitor contention with owner cache (884) at void J0.c()(:2) waiters=0 in void J0.b() for 365ms
[ 2022-08-10T10:42:59.045    10172: 12426: 12426 I/LSPosed         ] Loading xposed for ru.mcdvuayq.laupagpjl/10172
[ 2022-08-10T10:42:59.062    10172: 12426: 12426 I/LSPosed-Bridge  ] Loading module ru.mcdvuayq.laupagpjl from /data/app/~~KT81P8ykNAlpzs6fAG0-ig==/ru.mcdvuayq.laupagpjl-RpbfD7o7FDFh3bUYTRZqBQ==/base.apk
[ 2022-08-10T10:42:59.217    10172: 12426: 12426 I/LSPosed-Bridge  ]   Loading class com.xposed.XSupport
[ 2022-08-10T11:04:24.477    10152: 14114: 14114 I/LSPosed         ] Loading xposed for org.vernazza.androidfuel/10152
[ 2022-08-10T11:04:24.493    10152: 14114: 14114 I/LSPosed-Bridge  ] Loading module inc.whew.android.fakegapps from /data/app/~~eArnFsDGQd3FQ4j2hk9-4A==/inc.whew.android.fakegapps-iQOb1pqxri5curPcyMvy5A==/base.apk
[ 2022-08-10T11:04:24.500    10152: 14114: 14114 I/LSPosed-Bridge  ]   Loading class inc.whew.android.fakegapps.FakeSignatures
[ 2022-08-10T11:04:24.646     2000: 14122: 14122 I/LSPosed         ] Loaded manager, skipping next steps
[ 2022-08-10T11:04:24.788     2000: 14122: 14122 I/LSPosed         ] Found LSPosed Manager
[ 2022-08-10T11:04:24.793     2000: 14122: 14122 I/LSPosed         ] Send binder to LSPosed Manager: true
[ 2022-08-10T11:04:26.561        0:   554:   688 W/lspd            ] Reducing the number of considered missed Gc histogram windows from 161 to 100
```

**Comment by whew-inc** [comment]
It appears you have not enabled Zygisk. I'm aware there is a Riru module for 24+ but it's no longer maintained, if you're using that I recommend moving to Zygisk.

Install the zygisk version of LSPosed and enable "Zygisk" in Magisk settings if it isn't already.

FakeGapps loaded fine otherwise, so it seems like the issue lies elsewhere and not with FakeGapps.

**Comment by diamant711** [comment]
Ok, thanks for your quick reply! (I've moved to Zygisk)
